import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const errors=[];page.on('pageerror', e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173');
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'/tmp/father-welcome.png',fullPage:true});
await page.click('#play');
await page.keyboard.down('Space');await page.waitForTimeout(100);await page.keyboard.up('Space');
assert.equal(await page.locator('#strokes').textContent(),'00');
await page.keyboard.down('ArrowRight');await page.waitForTimeout(380);await page.keyboard.up('ArrowRight');
await page.keyboard.down('Space');await page.waitForTimeout(500);await page.keyboard.up('Space');
assert.equal(await page.locator('#strokes').textContent(),'01');
await page.screenshot({path:'/tmp/father-action.png',fullPage:true});
await page.locator('#victory').waitFor({state:'visible',timeout:12000});
assert.match(await page.locator('#result').textContent(),/Un colpo/);
await page.screenshot({path:'/tmp/father-victory.png',fullPage:true});
await page.click('#again');
assert.equal(await page.locator('#strokes').textContent(),'00');
assert.equal(await page.locator('#victory').isVisible(),false);
await page.click('#sound');assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/father-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser checks passed: miss, movement, charge, hit, portal victory, restart, audio toggle, responsive layout; no JavaScript errors.');
