import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
await page.clock.install({time:new Date('2026-10-06T12:00:00Z')});
await page.clock.pauseAt(new Date('2026-10-06T12:00:01Z'));
const errors=[];page.on('pageerror', e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173');
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'/tmp/father-welcome.png',fullPage:true});
await page.click('#play');
await page.keyboard.press('s');await page.clock.runFor(220);
await page.screenshot({path:'/tmp/father-jump.png'});
await page.keyboard.press('r');
await page.keyboard.down('a');await page.clock.runFor(100);await page.keyboard.up('a');
assert.equal(await page.locator('#strokes').textContent(),'00');
await page.keyboard.down('ArrowRight');await page.clock.runFor(500);await page.keyboard.up('ArrowRight');
await page.keyboard.down('a');await page.clock.runFor(625);await page.screenshot({path:'/tmp/father-charge.png'});await page.keyboard.up('a');
await page.clock.runFor(250);
assert.equal(await page.locator('#strokes').textContent(),'01');
await page.screenshot({path:'/tmp/father-action.png',fullPage:true});
await page.clock.runFor(9000);
await page.locator('#victory').waitFor({state:'visible',timeout:12000});
assert.match(await page.locator('#result').textContent(),/Un colpo/);
await page.screenshot({path:'/tmp/father-victory.png',fullPage:true});
await page.click('#again');
assert.equal(await page.locator('#strokes').textContent(),'00');
assert.equal(await page.locator('#victory').isVisible(),false);
await page.keyboard.down('ArrowRight');await page.clock.runFor(1000);
await page.keyboard.press('s');await page.clock.runFor(430);await page.keyboard.up('ArrowRight');
await page.clock.runFor(750);
await page.screenshot({path:'/tmp/father-platform.png',fullPage:true});
await page.click('#sound');assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/father-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser checks passed: S jump, miss, movement, A charge, hit, portal victory, restart, audio toggle, responsive layout; no JavaScript errors.');
